repository:
  name: clipflow
  description: "🎬 ClipFlow -- AI-powered Shorts/Reels automation: analyze → captions → highlights → render → publish"
  homepage: "https://github.com/raufA1/clipflow"
  private: false
  has_issues: true
  has_wiki: false
  has_projects: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true

topics:
  - ai
  - automation
  - video
  - youtube-shorts
  - tiktok
  - instagram-reels
  - content-automation
  - clipflow
  - python
  - flask
  - github-actions

labels:
  - name: enhancement
    color: a2eeef
    description: "New feature or improvement"
  - name: documentation
    color: 0075ca
    description: "Docs, guides, READMEs"
  - name: bug
    color: d73a4a
    description: "Something isn't working"