version: '3.8'
services:
  bot:
    build:
      context: ./services/bot
    restart: always
    env_file:
      - .env
  scheduler:
    build:
      context: ./services/scheduler
    ports:
      - "8081:8081"
    restart: always
    env_file:
      - .env
